name: Generate json files # games/index.json and games/owners.json

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate index.json and owners.json
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const dir = 'games';

          // Build index.json
          const files = fs.readdirSync(dir).filter(f => f.endsWith('.json') && f !== 'index.json');
          const entries = files.map(f => {
            const json = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf-8'));
            return {
              slug: f.replace('.json', ''),
              owner: json.owner || null,
              comingSoon: !!json.comingSoon
            };

            return { slug: f.replace('.json', ''), owner: json.owner || null };
          }).filter(Boolean);

          fs.writeFileSync(path.join(dir, 'index.json'), JSON.stringify(entries, null, 2));

          // Build owners.json
          const uniqueOwners = [...new Set(entries.map(e => e.owner).filter(Boolean))].sort();
          fs.writeFileSync(path.join(dir, 'owners.json'), JSON.stringify(uniqueOwners, null, 2));
          "

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add games/index.json games/owners.json
          git commit -m "Update games index.json and owners.json" || echo "No changes"
          git push
