name: Collect Owner Poll Reactions

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect_owners_votes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load latest owner poll message
        run: |
          mkdir -p .tmp
          RESPONSE=$(curl -s -X GET "https://discord.com/api/v10/channels/${{ secrets.DISCORD_OWNERS_CHANNEL_ID }}/messages?limit=1" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}")

          echo "$RESPONSE" > .tmp/latest_owner_message.json
          OWNER_POLL_ID=$(jq -r '.[0].id' .tmp/latest_owner_message.json)
          echo "OWNER_POLL_ID=$OWNER_POLL_ID" >> "$GITHUB_ENV"

      - name: Fetch poll message
        run: |
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X GET "https://discord.com/api/v10/channels/${{ secrets.DISCORD_OWNERS_CHANNEL_ID }}/messages/${OWNER_POLL_ID}" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}")

          HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS | cut -d: -f2)
          JSON_CONTENT=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')

          if [ "$HTTP_STATUS" != "200" ]; then
            echo "⚠️ Owner poll message not found or deleted (status $HTTP_STATUS). Skipping."
            exit 0
          fi

          echo "$JSON_CONTENT" > .poll_owner_message.json

      - name: Generate owners_results.json
        run: |
          mkdir -p results results/owners
          EMOJIS=(🇦 🇧 🇨 🇩 🇪 🇫 🇬 🇭 🇮 🇯 🇰 🇱 🇲 🇳 🇴 🇵 🇶 🇷 🇸 🇹 🇺 🇻 🇼 🇽 🇾 🇿)

          jq -r '.reactions[]? | "\(.emoji.name) \(.count)"' .poll_owner_message.json > .reaction_counts.txt || true

          NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          TODAY=$(date -u +'%Y-%m-%d')
          OWNERS=$(jq -r '.[]' games/owners.json)

          echo "{" > results/owners_results.json
          echo "  \"present\": [" >> results/owners_results.json

          i=0
          FIRST=true
          while read -r OWNER; do
            EMOJI=${EMOJIS[i]}
            RAW=$(grep "$EMOJI" .reaction_counts.txt | awk '{print $2}')
            VOTES=${RAW:-0}
            if [ "$VOTES" -gt 1 ]; then  # at least one user vote + bot reaction
              if [ "$FIRST" = false ]; then echo "," >> results/owners_results.json; fi
              echo "    \"$OWNER\"" >> results/owners_results.json
              FIRST=false
            fi
            i=$((i + 1))
          done <<< "$OWNERS"

          echo "  ]," >> results/owners_results.json
          echo "  \"generatedAt\": \"$NOW\"" >> results/owners_results.json
          echo "}" >> results/owners_results.json

          cp results/owners_results.json "results/owners/${TODAY}.json"

      - name: Commit results
        run: |
          git config --global user.name "poll-bot"
          git config --global user.email "bot@example.com"
          git add results/owners_results.json results/owners/*.json
          git commit -m "Update owner poll results and archive" || echo "No changes"
          git push || echo "Nothing to push"
